version: '3'

services:
  app:
    build: .
    volumes:
      - ./app/:/home/local/app/
    ports:
      - "8080:8080"
    stdin_open: true
    tty: true
    # command: >
    #   sh -c "
    #     go run main.go
    #   "
